CUDA_VISIBLE_DEVICES=1 python run.py \
    --output_dir=./saved_models_treevul \
    --model_type=roberta \
    --tokenizer_name=microsoft/codebert-base \
    --model_name_or_path=microsoft/codebert-base \
    --do_eval \
    --do_test \
    --train_data_file=../../../all_data/RQ4_data/treevul_data/train.jsonl \
    --eval_data_file=../../../all_data/RQ4_data//treevul_data/valid.jsonl \
    --test_data_file=../../../all_data/RQ4_data/treevul_data/test.jsonl \
    --epoch 5 \
    --block_size 200 \
    --train_batch_size 16 \
    --eval_batch_size 32 \
    --learning_rate 1e-5 \
    --max_grad_norm 1.0 \
    --evaluate_during_training \
    --seed 123456 2>&1 | tee test_treevul.log
